### ISSUE TITLE
Could you push a tag, please?

### ISSUE THREAD

**Issue by srenatus** [dchest/siphash#13]
Heya -- Thanks for providing this library.

From the last (and first 😄) release 1.0.0, quite [a few changes have been merged](https://github.com/dchest/siphash/compare/v1.0.0...master).

When libraries depend on siphash's functionality from "after 1.0.0", they can use some dependency management tool to pin a git ref. However, when the siphash package is pulled in _as a transitive dependency_ via `dep`, that utility will pick up the latest semver-ish looking tag. In this case, this would be 1.0.0 and can lead to some hard-to-find bugs that could be avoided 😉 

So, for users of `dep`, it would be super convenient if there was a more recent tag.

Would you be willing to push one? 😃 
Cheers

**Comment by dchest** [comment]
Done (v1.1.0). Thank you for noticing!
