### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by fgrosse** [dchest/siphash#16]
I would like to use this library but it doesn't specify a license so maybe you can add one?

There is a good tutorial how to do this quickly on github: https://help.github.com/articles/adding-a-license-to-a-repository

Personally I prefer the [BSD-3-Clause license][1] for my projects but obviously thats up to you to decide :)

[1]: https://opensource.org/licenses/BSD-3-Clause

**Comment by dchest** [comment]
It's here: https://github.com/dchest/siphash#public-domain-dedication

I guess I should put it in LICENSE so that it would be easier to find, but I don't think GitHub recognizes CC0.
